### ISSUE TITLE
Can confirm it works on my machine, and some notes to make it work

### ISSUE THREAD

**Issue by woct0rdho** [jakaline-dev/Triton_win#2]
After manually fixing some paths, it actually compiles things using ptxas. For running Flux and  CogVideoX, it runs almost as fast as on WSL on the same machine

I'm using 3080 Ti, CUDA 12.5, Python 3.10, torch 2.4.1, VS Build Tools 17.11.5

I installed the v3.0.0 release here, which is actually based on the official v2.2.0 looking from the commit history

Then I patched `triton/runtime/build.py` by
```patch
@@ -18,12 +18,19 @@
         sys.stdout, sys.stderr = old_stdout, old_stderr


-def _cc_cmd(cc, src, out, library_dirs, include_dirs, libraries):
+def _cc_cmd(cc, src, out, include_dirs, library_dirs, libraries):
     if cc in ["cl", "clang-cl"]:
         cc_cmd = [cc, src, "/nologo", "/O2", "/LD"]
         cc_cmd += [f"/I{dir}" for dir in include_dirs]
+        cc_cmd += [r"/IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.41.34120\include"]
+        cc_cmd += [r"/IC:\Program Files (x86)\Windows Kits\10\Include\10.0.26100.0\shared"]
+        cc_cmd += [r"/IC:\Program Files (x86)\Windows Kits\10\Include\10.0.26100.0\ucrt"]
+        cc_cmd += [r"/IC:\Program Files (x86)\Windows Kits\10\Include\10.0.26100.0\um"]
         cc_cmd += ["/link"]
         cc_cmd += [f"/LIBPATH:{dir}" for dir in library_dirs]
+        cc_cmd += [r"/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.41.34120\lib\x64"]
+        cc_cmd += [r"/LIBPATH:C:\Program Files (x86)\Windows Kits\10\Lib\10.0.26100.0\ucrt\x64"]
+        cc_cmd += [r"/LIBPATH:C:\Program Files (x86)\Windows Kits\10\Lib\10.0.26100.0\um\x64"]
         cc_cmd += [f'{lib}.lib' for lib in libraries]
         cc_cmd += [f"/OUT:{out}"]
     else:
@@ -48,6 +55,8 @@
         clang = shutil.which("clang")
         gcc = shutil.which("gcc")
         cc = gcc if gcc is not None else clang
+        if os.name == "nt":
+            cc = "cl"
         if cc is None:
             raise RuntimeError("Failed to find C compiler. Please specify via CC environment variable.")
     # This function was renamed and made public in Python 3.10
```
and `triton/backends/nvidia/compiler.py` by
```patch
@@ -304,6 +304,7 @@
     paths = [
         os.environ.get(f"TRITON_{binary.upper()}_PATH", ""),
         os.path.join(os.path.dirname(__file__), "bin", binary),
+        fr"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.5\bin\{binary}"
     ]

     for p in paths:
```

Update: I'm working on my own fork now, feel free to discuss there
https://github.com/woct0rdho/triton/tree/windows-fix

**Comment by FurkanGozukara** [comment]
Can you publish a wheel that can be installed for python 3.10?

**Comment by woct0rdho** [comment]
These patches are specific to my environment. If anyone knows how to properly detect these paths on other machines, welcome your help

**Comment by FurkanGozukara** [comment]
i also dont know how to compile wheel

**Comment by frankyifei** [comment]
It should be fairly easy to find all these path because if vs tools are properly installed, these path should be in your system path

**Comment by frankyifei** [comment]
I somehow got it to work, I have to add more includes and libs, CUDA and python, and --disable-cuda-malloc
```
def _cc_cmd(cc, src, out, library_dirs, include_dirs, libraries):
    if cc in ["cl", "clang-cl"]:
        cc_cmd = [cc, src, "/nologo", "/O2", "/LD"]
        cc_cmd += [f"/I{dir}" for dir in include_dirs]
        cc_cmd += [r"/IF:\MSBuild\VC\Tools\MSVC\14.39.33519\include"]
        cc_cmd += [r"/IF:\MSBuild\Windows Kits\10\Include\10.0.26100.0\shared"]
        cc_cmd += [r"/IF:\MSBuild\Windows Kits\10\Include\10.0.26100.0\ucrt"]
        cc_cmd += [r"/IF:\MSBuild\Windows Kits\10\Include\10.0.26100.0\um"]
        cc_cmd += [r"/IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4\include"]
        cc_cmd += ["/link"]
        cc_cmd += [f"/LIBPATH:{dir}" for dir in library_dirs]
        cc_cmd += [r"/LIBPATH:F:\MSBuild\VC\Tools\MSVC\14.39.33519\lib\x64"]
        cc_cmd += [r"/LIBPATH:F:\MSBuild\Windows Kits\10\Lib\10.0.26100.0\ucrt\x64"]
        cc_cmd += [r"/LIBPATH:F:\MSBuild\Windows Kits\10\Lib\10.0.26100.0\um\x64"]
        cc_cmd += [r"/LIBPATH:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4\lib\x64"]
        cc_cmd += [r"/LIBPATH:C:\Users\frank\AppData\Local\Programs\Python\Python310\libs"]
        cc_cmd += [f'{lib}.lib' for lib in libraries]
        cc_cmd += [f"/OUT:{out}"]
```
Before adding these the compile will run but will get a error related this error:

> CalledProcessError: Command '['cl', 'C:\\Users\\frank\\AppData\\Local\\Temp\\tmpoam57nwo\\main.c', '/nologo', '/O2', '/LD', '/IF:\\Comfy\\python_embeded\\Lib\\site-packages\\triton\\backends\\nvidia\\lib', '/IF:\\Comfy\\python_embeded\\libs', '/IC:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.4\\lib\\x64', '/IF:\\MSBuild\\VC\\Tools\\MSVC\\14.39.33519\\include', '/IF:\\MSBuild\\Windows Kits\\10\\Include\\10.0.26100.0\\shared', '/IF:\\MSBuild\\Windows Kits\\10\\Include\\10.0.26100.0\\ucrt', '/IF:\\MSBuild\\Windows Kits\\10\\Include\\10.0.26100.0\\um', '/IC:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.4\\include', '/link', '/LIBPATH:F:\\Comfy\\python_embeded\\Lib\\site-packages\\triton\\backends\\nvidia\\include', '/LIBPATH:C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.4\\include', '/LIBPATH:C:\\Users\\frank\\AppData\\Local\\Temp\\tmpoam57nwo', '/LIBPATH:F:\\Comfy\\python_embeded\\Include', '/LIBPATH:F:\\MSBuild\\VC\\Tools\\MSVC\\14.39.33519\\lib\\x64', '/LIBPATH:F:\\MSBuild\\Windows Kits\\10\\Lib\\10.0.26100.0\\ucrt\\x64', '/LIBPATH:F:\\MSBuild\\Windows Kits\\10\\Lib\\10.0.26100.0\\um\\x64', '/LIBPATH:C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.4\\lib\\x64', 'cuda.lib', '/OUT:C:\\Users\\frank\\AppData\\Local\\Temp\\tmpoam57nwo\\cuda_utils.cp311-win_amd64.pyd']' returned non-zero exit status 2.

Now the compile would finish without major error but still I feel something is not right. It still throw some errors. There is no major speedup on my 3060.

**Comment by jakaline-dev** [comment]
This repo is just a direct mirror from https://github.com/wkpark/triton. Better to inquire him than me.

**Comment by woct0rdho** [comment]
> This repo is just a direct mirror from https://github.com/wkpark/triton. Better to inquire him than me.

True but that repo does not have the place for issues. I'm working on my own fork now, feel free to discuss there:
https://github.com/woct0rdho/triton/tree/windows-fix

**Comment by FurkanGozukara** [comment]
@woct0rdho awesome thank you so much starred and watching

**Comment by osadchi** [comment]
I've followed the guide, but no luck so far..
https://github.com/woct0rdho/triton/issues/2

**Comment by shivshankar11** [comment]
cant we add libs and include folder to wheel?

**Comment by jakaline-dev** [comment]
@shivshankar11 
https://github.com/woct0rdho/triton-windows/releases/tag/v3.1.0-windows.post4
Wheels are up
